Settings:
  make-enabled-worlds-a-blacklist: false
  enabled-worlds:
    - "world"
    - "world_nether"
    - "world_the_end"
  use-explosion-radius: false
  radius-check: 3
  drain-chance: 0.9

Messages:
  config-reloaded: "&aConfiguration Reloaded!"
  no-permissions: "&cYou must have the &f%perm% &cpermission!"